"""empty message

Revision ID: 36e8f0ca4136
Revises: 68e143ab23b9
Create Date: 2022-08-21 22:04:28.796034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36e8f0ca4136'
down_revision = '68e143ab23b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('number',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=25), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provided_to', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('number')
    # ### end Alembic commands ###
